### ISSUE TITLE
feat: 기록의 스티커 post api 개발

### ISSUE THREAD

**Issue by yujeongkimm** [Kusitms-Tikkle/tikkle-server#56]
## Description

v.1.1.0

## Todo

- [x] 스티커 생성 메서드 작성하기
- [x] 기록과 연관관계 편의 메서드 작성하기
- [x] 스티커 post api 개발하기 
  - dtype(a,b,c)으로 스티커 종류 구분
