### ISSUE TITLE
feat: 기록의 스티커 취소 api 개발

### ISSUE THREAD

**Issue by yujeongkimm** [Kusitms-Tikkle/tikkle-server#58]
## Description

v.1.1.0

## Todo

- [x] 스티커 취소 api 개발
- [x] Memo에 cascade 옵션 추가
- [x] Sticker 예외 처리 코드 추가
